site_name: My Docs
nav:
    - "index.md"
    - "define.md"
    - "reference.md"

theme:
    name: material
    language: en

use_directory_urls: false

plugins:
    - search
    - htmlproofer

markdown_extensions:
    - attr_list:
    - toc:
        permalink: true
